#!/bin/bash
ID=$(id -u)

USR=$1

if [ $# != 1 ]
then
	printf "Enter active user to delete\n"
	exit 1
fi

if [ $ID != 0 ]
then
	printf "Must be run as root!\n"
	exit 1
else
	pgrep -u $1
	ps -fp $(pgrep -u $1)
	killall -KILL -u $1
	/sbin/userdel -r $1
fi
